version: "3.8"

services:

  redis:
    image: redis:alpine
    profiles:
      - cache_database
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    command: redis-server --requirepass local-redis-pass
    networks:
      - mongo-network

  mongo:
    image: mongo:latest
    profiles:
      - cache_database
      - database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network
      
  # ui for mongo
  mongo-express:
    image: mongo-express
    restart: always
    profiles:
      - cache_database
      - database
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_DATABASE: mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
    name: mongo-network